version: '3.8'

services:
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bitcamp
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - backend

  web:
    build: .
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py collectstatic --noinput &&
             gunicorn bitcamp.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
      - web_media:/code/media
      - web_static:/code/static
    environment:
      - SECRET_KEY=BitCamp-სწავლა-და-ბრძოლა-1024
      - DEBUG=False
      - DISCORD_BOT_TOKEN=<bot_token>
      - DB_NAME=bitcamp
      - DB_USER=user
      - DB_PASS=password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - web_media:/code/media
      - web_static:/code/static
      - certbot-etc:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - backend

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - web_static:/code/static
    depends_on:
      - nginx
    # command: certonly --webroot --webroot-path=/code/static --email <your-email> --agree-tos --no-eff-email --force-renewal -d <your-domain> -d <your-domain>

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  web_media:
  web_static:
  certbot-etc:
