# Generated by Django 5.0.2 on 2024-03-08 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_kidsprofile_delete_discorduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='last_payment',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='start_payment',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 14, 44, 52, 652696, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
