name: Build and Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker-compose -f docker-compose.yml build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to DigitalOcean
      run: |
        cd $GITHUB_WORKSPACE
        ls -R
        ls -R ./
        ls -R $GITHUB_WORKSPACE
        docker-compose -f docker-compose.yml down --volumes --remove-orphans
        docker-compose -f docker-compose.yml up -d
